image:
  repository: repodocker2025/webcommerce
  tag: "73236510"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

persistence:
  size: 1Gi
  storageClassName: gp2  # Valeur remplacée par le pipeline (ex: gp2 pour EKS)
