image:
  repository: repodocker2025/webcommerce
  tag: "f473a7d5"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  WORDPRESS_DATABASE_HOST: mysqlcommerce
  WORDPRESS_DATABASE_PORT_NUMBER: "3306"
  WORDPRESS_DATABASE_NAME: wordpress    # ✅ cohérent avec mysqlcommerce
  WORDPRESS_DATABASE_USER: wp_user
  WORDPRESS_DATABASE_PASSWORD: wp_pass2025
  WORDPRESS_ENABLE_DATABASE_SSL: "no"  # 🔒 SSL désactivé pour la connexion locale K3S

persistence:
  enabled: true
  size: 1Gi
  storageClassName: gp2
  mountPath: /bitnami/wordpress
  claimName: wp-pvc

replicaCount: 1

podSecurityContext:
  fsGroup: 1001

containerSecurityContext:
  runAsUser: 1001
  runAsGroup: 1001

volumePermissions:
  enabled: true  # ✅ corrige les erreurs d'écriture sur les fichiers montés

startupProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 30

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 5
