image:
  repository: salim2025/webcommerce
  tag: "latest"
  pullPolicy: Always

env:
  WORDPRESS_DB_HOST: mysqlcommerce.deploy.svc.cluster.local
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_PASSWORD: "1234"
  WORDPRESS_DB_NAME: wordpress

persistence:
  enabled: true
  size: 5Gi

service:
  type: ClusterIP
  port: 80
