image:
  repository: repodocker2025/webcommerce
  tag: "06d4624c"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  WORDPRESS_DATABASE_HOST: mysqlcommerce
  WORDPRESS_DATABASE_PORT_NUMBER: "3306"
  WORDPRESS_DATABASE_NAME: wp_db
  WORDPRESS_DATABASE_USER: wp_user
  WORDPRESS_DATABASE_PASSWORD: wp_pass2025
  WORDPRESS_ENABLE_DATABASE_SSL: "no"  # SSL désactivé pour la connexion locale K3S

persistence:
  enabled: true
  size: 1Gi
  storageClassName: gp2  # Pour K3S
  mountPath: /bitnami/wordpress
  claimName: wp-pvc

podSecurityContext:
  fsGroup: 1001  # ✅ Autorise l'utilisateur 1001 à écrire sur le volume monté

containerSecurityContext:
  runAsUser: 1001
  runAsNonRoot: true  # ✅ Bonnes pratiques de sécurité

monitoring:
  enabled: false  # Aucune intégration Prometheus/Exporter nécessaire ici
