apiVersion: v1
kind: Service
metadata:
  name: {{ include "webcommerce.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "webcommerce.name" . }}
    helm.sh/chart: {{ include "webcommerce.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "webcommerce.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
