apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webcommerce-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: webcommerce.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: webcommerce-service
                port:
                  number: {{ .Values.service.port }}
  tls:
    - secretName: webcommerce-tls
      hosts:
        - webcommerce.local
