apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webcommerce-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "5Gi" }}
