apiVersion: v1
kind: Service
metadata:
  name: webcommerce-service
  labels:
    app: webcommerce
    expose: "true"
spec:
  selector:
    app: webcommerce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
