apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webcommerce-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass | default "local-path" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "5Gi" }}
