apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlcommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlcommerce
  template:
    metadata:
      labels:
        app: mysqlcommerce
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.pod.fsGroup }}
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-auth
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-auth
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-auth
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-auth
                  key: mysql-password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-pv
              mountPath: /bitnami/mysql/data
          securityContext:
            runAsUser: {{ .Values.securityContext.container.runAsUser }}
            runAsGroup: {{ .Values.securityContext.container.runAsGroup }}
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName }}
