apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlcommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlcommerce
  template:
    metadata:
      labels:
        app: mysqlcommerce
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.env.MYSQL_ROOT_PASSWORD }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.env.MYSQL_DATABASE }}"
            - name: MYSQL_USER
              value: "{{ .Values.env.MYSQL_USER }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.env.MYSQL_PASSWORD }}"
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-pv
              mountPath: "{{ .Values.persistence.mountPath }}"
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: "{{ .Values.persistence.claimName }}"
