apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlcommerce
  labels:
    app: mysqlcommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlcommerce
  template:
    metadata:
      labels:
        app: mysqlcommerce
    spec:
      containers:
        - name: mysqlcommerce
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlcommerce-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: wordpress
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysqlcommerce-pvc
