apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlcommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlcommerce
  template:
    metadata:
      labels:
        app: mysqlcommerce
    spec:
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.env.MYSQL_ROOT_PASSWORD }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.env.MYSQL_DATABASE }}"
            - name: MYSQL_USER
              value: "{{ .Values.env.MYSQL_USER }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.env.MYSQL_PASSWORD }}"
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-pv
              mountPath: "{{ .Values.persistence.mountPath }}"

{{- if .Values.monitoring.enabled }}
        - name: mysqld-exporter
          image: prom/mysqld-exporter:latest
          ports:
            - name: metrics
              containerPort: 9104
          env:
            - name: DATA_SOURCE_NAME
              value: "{{ .Values.env.MYSQL_USER }}:{{ .Values.env.MYSQL_PASSWORD }}@(localhost:3306)/"
{{- end }}

      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: "{{ .Values.persistence.claimName }}"
