apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlcommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlcommerce
  template:
    metadata:
      labels:
        app: mysqlcommerce
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysqlRootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysqlDatabase }}"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql

        - name: mysqld-exporter
          image: prom/mysqld-exporter:v0.14.0
          ports:
            - name: metrics
              containerPort: 9104
          env:
            - name: DATA_SOURCE_NAME
              value: "root:{{ .Values.mysqlRootPassword }}@(localhost:3306)/"
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
