apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlcommerce-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "10Gi" }}
