apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlcommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlcommerce
  template:
    metadata:
      labels:
        app: mysqlcommerce
    spec:
      containers:
        - name: mysqlcommerce
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.password }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.database }}"
            - name: MYSQL_USER
              value: "{{ .Values.mysql.user }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysql.password }}"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysqlcommerce-pvc
