apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlcommerce-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2          # <-- doit être défini explicitement
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "10Gi" }}
