apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlcommerce-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "10Gi" | quote }}
