apiVersion: v1
kind: Service
metadata:
  name: mysqlcommerce
  labels:
    app: mysqlcommerce
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
  selector:
    app: mysqlcommerce
