apiVersion: v1
kind: Service
metadata:
  name: mysqlcommerce
spec:
  selector:
    app: mysqlcommerce
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3306
  type: {{ .Values.service.type }}
