image:
  repository: bitnami/mysql
  tag: "5.7"
  pullPolicy: IfNotPresent

auth:
  rootPassword: root_pass2025
  database: wp_db
  username: wp_user
  password: wp_pass2025

persistence:
  enabled: true
  size: 1Gi
  storageClass: local-path
  existingClaim: mysql-pvc

primary:
  service:
    type: ClusterIP
    ports:
      mysql: 3306
