image:
  repository: mysql
  tag: "8.0"  # Pas modifié par le pipeline, donc reste en "latest" pour les pods

mysqlRootPassword: rootpassword
mysqlDatabase: wordpress

persistence:
  size: 1Gi
  storageClassName: gp2  # Valeur remplacée par le pipeline GitLab si besoin (ex: gp2)
