image:
  registry: docker.io
  repository: bitnami/mysql
  tag: 8.0.36

auth:
  enabled: true   # 👈 INDISPENSABLE
  rootPassword: rootpassword
  database: wp_db
  username: wp_user
  password: wp_pass2025

primary:
  service:
    type: ClusterIP
    port: 3306

  persistence:
    enabled: true
    storageClass: local-path
    size: 1Gi

  configuration: |
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port=3306
    ssl=0

  podSecurityContext:
    enabled: true
    fsGroup: 1001

  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001

metrics:
  enabled: false

volumePermissions:
  enabled: true
