image:
  repository: bitnami/mysql
  tag: 8.0.36
  pullPolicy: IfNotPresent

auth:
  existingSecret: mysql-auth

primary:
  persistence:
    enabled: true
    storageClass: local-path
    size: 1Gi
    claimName: mysql-pvc

  configuration: |
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port=3306
    ssl=0

  podSecurityContext:
    enabled: true
    fsGroup: 1001

  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
