image:
  repository: bitnami/mysql
  tag: "5.7"
  pullPolicy: IfNotPresent

env:
  MYSQL_ROOT_PASSWORD: root_pass2025
  MYSQL_DATABASE: wp_db
  MYSQL_USER: wp_user
  MYSQL_PASSWORD: wp_pass2025

persistence:
  enabled: true
  size: 1Gi
  storageClassName: gp2  # ✅ Pour K3S
  mountPath: /bitnami/mysql
  claimName: mysql-pvc

service:
  type: ClusterIP
  port: 3306

monitoring:
  enabled: false  # ✅ On désactive le conteneur exporter pour éviter les erreurs (optionnel mais recommandé)

podSecurityContext:
  fsGroup: 1001  # ✅ Autorise l’utilisateur 1001 à écrire dans le volume monté
