image:
  repository: registry.gitlab.com/lachuernet/devops_webservice/mysqlcommerce
  tag: "latest"

mysql:
  database: "wordpress"
  user: "root"
  password: "1234"

persistence:
  enabled: true
  size: 10Gi

service:
  port: 3306
